GET http://localhost:3000/api/genres 

###
POST http://localhost:3000/api/genres 
Content-Type: application/json

{
    "name":"New Course"
}

###
PUT http://localhost:3000/api/genres/3
Content-Type: application/json

{  
    "name":"New Node Course"
}

###
DELETE http://localhost:3000/api/genres/1